apiVersion: v1
kind: Pod 
metadata:
  name: course-app  
  namespace: infra  
  labels:
    aadpodidbinding: course-identity
spec: 
  containers: 
  - name: course-app   
    image: busybox 
    args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']  